// src/components/Help.vue
<template>
  <v-card class="elevation-24">
    <v-toolbar dark flat>
      <v-toolbar-title style="font-weight: bold">Pointland Usage</v-toolbar-title>
    </v-toolbar>

    <!-- Shortcuts -->
    <v-expansion-panels>
      <v-expansion-panel>
        <v-expansion-panel-header>
          <v-card-title style="font-weight: bold">Desktop</v-card-title>
        </v-expansion-panel-header>
        <v-expansion-panel-content>
          <v-divider />
          <v-card-subtitle>Desktop Move Shortcuts</v-card-subtitle>
          <v-card-text> <kbd>w</kbd> - Move front </v-card-text>
          <v-card-text> <kbd>a</kbd> - Move left </v-card-text>
          <v-card-text> <kbd>s</kbd> - Move right </v-card-text>
          <v-card-text> <kbd>d</kbd> - Move back </v-card-text>
          <v-card-text> <kbd>q</kbd> - Move down </v-card-text>
          <v-card-text> <kbd>e</kbd> - Move up </v-card-text>

          <v-card-subtitle>Desktop See Shortcuts</v-card-subtitle>
          <v-card-text> <kbd>up</kbd> - See up </v-card-text>
          <v-card-text> <kbd>left</kbd> - See left </v-card-text>
          <v-card-text> <kbd>down</kbd> - See down </v-card-text>
          <v-card-text> <kbd>right</kbd> - See right </v-card-text>
        </v-expansion-panel-content>
      </v-expansion-panel>

      <v-expansion-panel>
        <v-expansion-panel-header>
          <v-card-title style="font-weight: bold">Mobile</v-card-title>
        </v-expansion-panel-header>
        <v-expansion-panel-content>
          <v-divider />
          <v-card-subtitle>Mobile Move</v-card-subtitle>
          <v-card-text> <kbd>Left Bottom Area</kbd> - XY Plane Movement </v-card-text>
          <v-card-text> <kbd>Right Bottom Area</kbd> - Rotate Camera </v-card-text>
          <v-card-text> <kbd>Top Left Area</kbd> - Fast XY Plane Movement </v-card-text>
          <v-card-text> <kbd>Top Right Area</kbd> - XZ Plane Movement </v-card-text>
        </v-expansion-panel-content>
      </v-expansion-panel>
    </v-expansion-panels>
  </v-card>
</template>

// src/components/Help.tsx
import {
  Card,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from '@/components/ui/accordion'
import { Separator } from '@/components/ui/separator'

export const Help = () => {
  return (
    <Card className="shadow-2xl">
      <CardHeader className="bg-primary text-primary-foreground">
        <CardTitle>Pointland Usage</CardTitle>
      </CardHeader>

      <Accordion type="single" collapsible>
        <AccordionItem value="desktop">
          <AccordionTrigger>
            <CardTitle>Desktop</CardTitle>
          </AccordionTrigger>
          <AccordionContent>
            <Separator />
            <div className="p-4 space-y-4">
              <h3 className="text-sm font-medium text-muted-foreground">Desktop Move Shortcuts</h3>
              <div className="space-y-2">
                <p><kbd className="px-2 py-1 bg-muted rounded">w</kbd> - Move front</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">a</kbd> - Move left</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">s</kbd> - Move right</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">d</kbd> - Move back</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">q</kbd> - Move down</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">e</kbd> - Move up</p>
              </div>

              <h3 className="text-sm font-medium text-muted-foreground">Desktop See Shortcuts</h3>
              <div className="space-y-2">
                <p><kbd className="px-2 py-1 bg-muted rounded">↑</kbd> - See up</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">←</kbd> - See left</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">↓</kbd> - See down</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">→</kbd> - See right</p>
              </div>
            </div>
          </AccordionContent>
        </AccordionItem>

        <AccordionItem value="mobile">
          <AccordionTrigger>
            <CardTitle>Mobile</CardTitle>
          </AccordionTrigger>
          <AccordionContent>
            <Separator />
            <div className="p-4 space-y-4">
              <h3 className="text-sm font-medium text-muted-foreground">Mobile Move</h3>
              <div className="space-y-2">
                <p><kbd className="px-2 py-1 bg-muted rounded">Left Bottom Area</kbd> - XY Plane Movement</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">Right Bottom Area</kbd> - Rotate Camera</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">Top Left Area</kbd> - Fast XY Plane Movement</p>
                <p><kbd className="px-2 py-1 bg-muted rounded">Top Right Area</kbd> - XZ Plane Movement</p>
              </div>
            </div>
          </AccordionContent>
        </AccordionItem>
      </Accordion>
    </Card>
  )
}

export default Help
